dist: xenial

git:
  depth: false

language: python

python:
  - 3.8

install:
  - travis_retry pip install --upgrade pip setuptools wheel
  - travis_retry pip install -r requirements.txt -r requirements-test.txt

env:
  - MPLBACKEND=Agg

cache: pip

script:
  - pip install .
  - python -m pytest --randomly-seed=42 --randomly-dont-reorganize --cov=pyFlowSOM --pycodestyle pyFlowSOM

after_failure:
  - cat out.log

after_success:
  - coveralls