git:
  depth: false

jobs:
  include:
    - os: linux
      dist: xenial
      services: docker
      language: python
      python: "3.9"
      install:
        - python3 -m pip install setuptools 'Cython>=0.29,<1'
      script:
        - python3 setup.py sdist --dist-dir dist
    - os: linux
      dist: xenial
      services: docker
      language: python
      python: "3.9"
    - os: linux
      dist: xenial
      arch: arm64
      services: docker
      language: python
      python: "3.9"
    - os: windows
      language: shell
      before_install:
        - choco upgrade python -y --version 3.8.6
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        # make sure it's on PATH as 'python3'
        - ln -s /c/Python38/python.exe /c/Python38/python3.exe

install:
  - python3 -m pip install cibuildwheel==2.11.3

script:
  - python3 -m cibuildwheel --output-dir dist

# deploy to PyPI on tags
before_deploy: "python3 -m pip install twine"
deploy:
  provider: script
  edge: true
  script: twine upload dist/* -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD"
  cleanup: false
  on:
    tags: true