[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel", "numpy>=1,<2", "Cython>=0.29,<1"]

[project]
requires-python = ">=3.8"

[tool.cibuildwheel]
test-command = "pytest {project}/pyFlowSOM"
test-requires = ["pytest", "pandas"]
build-verbosity = 2
