[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyflowsom"
version = "0.1"
description = "Python wrapper for the FlowSOM algorithm."
dependencies = [
    "numpy == 1.23.*",
    ]